import React from 'react';

import './App.css';

const _ = require('lodash')

function App() {

  const renderSome = () => {
    const messagez = []
    messa.map(item => {

      if (_.isEmpty(messagez)) {
        messagez.push({ sender: item.sender, mess: [item.mess] })
      }
      else if (messagez[messagez.length - 1].sender === item.sender) {
        messagez[messagez.length - 1].mess.push(item.mess)
      } else {
        messagez.push({ sender: item.sender, mess: [item.mess] })
      }
      console.log(messagez)
    })

    return messagez.map(item => {
      const clazz = item.sender === 1 ? 'sender' : 'mine'
      return (
        <div className={clazz}>
          {
            item.mess.map((mess, index) => {
              return <li key={mess}>{mess}</li>
            })
          }
        </div>
      )
    })
  }

  return (
    <div className="App">
      <header className="App-header">
        <ul>
          {
            renderSome()
          }
        </ul>
      </header>
    </div>
  );
}


const messa = [
  {
    sender: 1,
    mess: 'a'
  },
  {
    sender: 1,
    mess: 'b'
  },
  {
    sender: 2,
    mess: 'c'
  },
  {
    sender: 1,
    mess: 'd'
  },
  {
    sender: 2,
    mess: 'e'
  },
  {
    sender: 2,
    mess: 'c'
  },
  {
    sender: 2,
    mess: 'd'
  },
]

//! REAL DATA
const data = {
  "user": {
    "hooks": "Object",
    "id": "1",
    "encodedId": "1",
    "serverInstanceV2": "Object",
    "serverInstanceV6": "Object",
    "filesInstance": "Object",
    "cursorsInstance": "Object",
    "connectionTimeout": 20000,
    "presenceInstance": "Object",
    "beamsTokenProviderInstance": "Object",
    "pushNotificationsInstance": "Object",
    "beamsInstanceInitFn": "fn()",
    "logger": "Object",
    "presenceStore": "Object",
    "userStore": "Object",
    "roomStore": "Object",
    "cursorStore": "Object",
    "typingIndicators": "Object",
    "roomSubscriptions": "Object",
    "readCursorBuffer": "Object",
    "userPresenceSubscriptions": "Object",
    "setReadCursor": "bound value()",
    "readCursor": "bound value()",
    "isTypingIn": "bound value()",
    "createRoom": "bound value()",
    "getJoinableRooms": "bound value()",
    "joinRoom": "bound value()",
    "leaveRoom": "bound value()",
    "addUserToRoom": "bound value()",
    "removeUserFromRoom": "bound value()",
    "sendMessage": "bound value()",
    "sendSimpleMessage": "bound value()",
    "sendMultipartMessage": "bound value()",
    "fetchMessages": "bound value()",
    "fetchMultipartMessages": "bound value()",
    "subscribeToRoom": "bound value()",
    "subscribeToRoomMultipart": "bound value()",
    "updateRoom": "bound value()",
    "deleteRoom": "bound value()",
    "setReadCursorRequest": "bound value()",
    "uploadDataAttachment": "bound value()",
    "isMemberOf": "bound value()",
    "isSubscribedTo": "bound value()",
    "decorateMessage": "bound value()",
    "setPropertiesFromBasicUser": "bound value()",
    "establishUserSubscription": "bound value()",
    "establishPresenceSubscription": "bound value()",
    "subscribeToUserPresence": "bound value()",
    "disconnect": "bound value()",
    "_uploadAttachment": "bound value()",
    "userSubscription": "Object",
    "presenceSubscription": "Object",
    "avatarURL": "http://justiva.loc/images/placeholder-woman.png",
    "createdAt": "2019-08-21T09:18:51Z",
    "customData": "Object",
    "name": "Admin Administrator",
    "updatedAt": "2019-10-16T09:34:13Z"
  },
  "room": {
    "createdAt": "2019-08-23T09:21:50Z",
    "createdByUserId": "1",
    "id": "b303155f-7baf-4fc0-92bc-c90caa223be0",
    "isPrivate": true,
    "name": "137162",
    "updatedAt": "2019-08-23T09:21:50Z",
    "unreadCount": 0,
    "lastMessageAt": "2019-09-25T14:11:45Z",
    "userIds": "Array[2]",
    "userStore": "Object",
    "isSubscribedTo": "isSubscribedTo()",
    "logger": "Object",
    "eq": "bound value()"
  },
  "rooms": [
    "Object",
    "Object",
    "Object",
    "Object",
    "Object",
    "Object",
    "Object",
    "Object",
    "Object",
    "Object",
    "Object",
    "Object",
    "Object",
    "Object",
    "Object",
    "Object"
  ],
  "messages": {
    "100343674": {
      "id": 100343674,
      "senderId": "37162",
      "roomId": "b303155f-7baf-4fc0-92bc-c90caa223be0",
      "createdAt": "2019-09-09T11:31:02Z",
      "updatedAt": "2019-09-09T11:31:02Z",
      "text": "а ты кто?",
      "userStore": {
        "instance": "Object",
        "presenceStore": "Object",
        "logger": "Object",
        "reqs": "Object",
        "onSetHooks": "Array[1]",
        "users": "Object",
        "set": "bound value()",
        "get": "bound value()",
        "fetchMissingUsers": "bound value()",
        "fetchBasicUsers": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      },
      "roomStore": {
        "instance": "Object",
        "userStore": "Object",
        "isSubscribedTo": "isSubscribedTo()",
        "logger": "Object",
        "rooms": "Object",
        "setSync": "bound value()",
        "set": "bound value()",
        "get": "bound value()",
        "popSync": "bound value()",
        "pop": "bound value()",
        "addUserToRoom": "bound value()",
        "removeUserFromRoom": "bound value()",
        "updateSync": "bound value()",
        "update": "bound value()",
        "fetchBasicRoom": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      }
    },
    "100343680": {
      "id": 100343680,
      "senderId": "1",
      "roomId": "b303155f-7baf-4fc0-92bc-c90caa223be0",
      "createdAt": "2019-09-09T11:32:57Z",
      "updatedAt": "2019-09-09T11:32:57Z",
      "text": "))))",
      "userStore": {
        "instance": "Object",
        "presenceStore": "Object",
        "logger": "Object",
        "reqs": "Object",
        "onSetHooks": "Array[1]",
        "users": "Object",
        "set": "bound value()",
        "get": "bound value()",
        "fetchMissingUsers": "bound value()",
        "fetchBasicUsers": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      },
      "roomStore": {
        "instance": "Object",
        "userStore": "Object",
        "isSubscribedTo": "isSubscribedTo()",
        "logger": "Object",
        "rooms": "Object",
        "setSync": "bound value()",
        "set": "bound value()",
        "get": "bound value()",
        "popSync": "bound value()",
        "pop": "bound value()",
        "addUserToRoom": "bound value()",
        "removeUserFromRoom": "bound value()",
        "updateSync": "bound value()",
        "update": "bound value()",
        "fetchBasicRoom": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      }
    },
    "100343681": {
      "id": 100343681,
      "senderId": "37162",
      "roomId": "b303155f-7baf-4fc0-92bc-c90caa223be0",
      "createdAt": "2019-09-09T11:33:07Z",
      "updatedAt": "2019-09-09T11:33:07Z",
      "text": "это тестовый?",
      "userStore": {
        "instance": "Object",
        "presenceStore": "Object",
        "logger": "Object",
        "reqs": "Object",
        "onSetHooks": "Array[1]",
        "users": "Object",
        "set": "bound value()",
        "get": "bound value()",
        "fetchMissingUsers": "bound value()",
        "fetchBasicUsers": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      },
      "roomStore": {
        "instance": "Object",
        "userStore": "Object",
        "isSubscribedTo": "isSubscribedTo()",
        "logger": "Object",
        "rooms": "Object",
        "setSync": "bound value()",
        "set": "bound value()",
        "get": "bound value()",
        "popSync": "bound value()",
        "pop": "bound value()",
        "addUserToRoom": "bound value()",
        "removeUserFromRoom": "bound value()",
        "updateSync": "bound value()",
        "update": "bound value()",
        "fetchBasicRoom": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      }
    },
    "100343682": {
      "id": 100343682,
      "senderId": "37162",
      "roomId": "b303155f-7baf-4fc0-92bc-c90caa223be0",
      "createdAt": "2019-09-09T11:33:14Z",
      "updatedAt": "2019-09-09T11:33:14Z",
      "text": "))",
      "userStore": {
        "instance": "Object",
        "presenceStore": "Object",
        "logger": "Object",
        "reqs": "Object",
        "onSetHooks": "Array[1]",
        "users": "Object",
        "set": "bound value()",
        "get": "bound value()",
        "fetchMissingUsers": "bound value()",
        "fetchBasicUsers": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      },
      "roomStore": {
        "instance": "Object",
        "userStore": "Object",
        "isSubscribedTo": "isSubscribedTo()",
        "logger": "Object",
        "rooms": "Object",
        "setSync": "bound value()",
        "set": "bound value()",
        "get": "bound value()",
        "popSync": "bound value()",
        "pop": "bound value()",
        "addUserToRoom": "bound value()",
        "removeUserFromRoom": "bound value()",
        "updateSync": "bound value()",
        "update": "bound value()",
        "fetchBasicRoom": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      }
    },
    "100343684": {
      "id": 100343684,
      "senderId": "1",
      "roomId": "b303155f-7baf-4fc0-92bc-c90caa223be0",
      "createdAt": "2019-09-09T11:33:31Z",
      "updatedAt": "2019-09-09T11:33:31Z",
      "text": "нет!",
      "userStore": {
        "instance": "Object",
        "presenceStore": "Object",
        "logger": "Object",
        "reqs": "Object",
        "onSetHooks": "Array[1]",
        "users": "Object",
        "set": "bound value()",
        "get": "bound value()",
        "fetchMissingUsers": "bound value()",
        "fetchBasicUsers": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      },
      "roomStore": {
        "instance": "Object",
        "userStore": "Object",
        "isSubscribedTo": "isSubscribedTo()",
        "logger": "Object",
        "rooms": "Object",
        "setSync": "bound value()",
        "set": "bound value()",
        "get": "bound value()",
        "popSync": "bound value()",
        "pop": "bound value()",
        "addUserToRoom": "bound value()",
        "removeUserFromRoom": "bound value()",
        "updateSync": "bound value()",
        "update": "bound value()",
        "fetchBasicRoom": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      }
    },
    "100343687": {
      "id": 100343687,
      "senderId": "37162",
      "roomId": "b303155f-7baf-4fc0-92bc-c90caa223be0",
      "createdAt": "2019-09-09T11:33:57Z",
      "updatedAt": "2019-09-09T11:33:57Z",
      "text": "удали себя",
      "userStore": {
        "instance": "Object",
        "presenceStore": "Object",
        "logger": "Object",
        "reqs": "Object",
        "onSetHooks": "Array[1]",
        "users": "Object",
        "set": "bound value()",
        "get": "bound value()",
        "fetchMissingUsers": "bound value()",
        "fetchBasicUsers": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      },
      "roomStore": {
        "instance": "Object",
        "userStore": "Object",
        "isSubscribedTo": "isSubscribedTo()",
        "logger": "Object",
        "rooms": "Object",
        "setSync": "bound value()",
        "set": "bound value()",
        "get": "bound value()",
        "popSync": "bound value()",
        "pop": "bound value()",
        "addUserToRoom": "bound value()",
        "removeUserFromRoom": "bound value()",
        "updateSync": "bound value()",
        "update": "bound value()",
        "fetchBasicRoom": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      }
    },
    "100344032": {
      "id": 100344032,
      "senderId": "1",
      "roomId": "b303155f-7baf-4fc0-92bc-c90caa223be0",
      "createdAt": "2019-09-09T13:27:37Z",
      "updatedAt": "2019-09-09T13:27:37Z",
      "text": "dsadsa",
      "userStore": {
        "instance": "Object",
        "presenceStore": "Object",
        "logger": "Object",
        "reqs": "Object",
        "onSetHooks": "Array[1]",
        "users": "Object",
        "set": "bound value()",
        "get": "bound value()",
        "fetchMissingUsers": "bound value()",
        "fetchBasicUsers": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      },
      "roomStore": {
        "instance": "Object",
        "userStore": "Object",
        "isSubscribedTo": "isSubscribedTo()",
        "logger": "Object",
        "rooms": "Object",
        "setSync": "bound value()",
        "set": "bound value()",
        "get": "bound value()",
        "popSync": "bound value()",
        "pop": "bound value()",
        "addUserToRoom": "bound value()",
        "removeUserFromRoom": "bound value()",
        "updateSync": "bound value()",
        "update": "bound value()",
        "fetchBasicRoom": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      }
    },
    "100344053": {
      "id": 100344053,
      "senderId": "1",
      "roomId": "b303155f-7baf-4fc0-92bc-c90caa223be0",
      "createdAt": "2019-09-09T13:35:14Z",
      "updatedAt": "2019-09-09T13:35:14Z",
      "text": "dsadsa",
      "userStore": {
        "instance": "Object",
        "presenceStore": "Object",
        "logger": "Object",
        "reqs": "Object",
        "onSetHooks": "Array[1]",
        "users": "Object",
        "set": "bound value()",
        "get": "bound value()",
        "fetchMissingUsers": "bound value()",
        "fetchBasicUsers": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      },
      "roomStore": {
        "instance": "Object",
        "userStore": "Object",
        "isSubscribedTo": "isSubscribedTo()",
        "logger": "Object",
        "rooms": "Object",
        "setSync": "bound value()",
        "set": "bound value()",
        "get": "bound value()",
        "popSync": "bound value()",
        "pop": "bound value()",
        "addUserToRoom": "bound value()",
        "removeUserFromRoom": "bound value()",
        "updateSync": "bound value()",
        "update": "bound value()",
        "fetchBasicRoom": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      }
    },
    "100344054": {
      "id": 100344054,
      "senderId": "1",
      "roomId": "b303155f-7baf-4fc0-92bc-c90caa223be0",
      "createdAt": "2019-09-09T13:35:15Z",
      "updatedAt": "2019-09-09T13:35:15Z",
      "text": "dsada",
      "userStore": {
        "instance": "Object",
        "presenceStore": "Object",
        "logger": "Object",
        "reqs": "Object",
        "onSetHooks": "Array[1]",
        "users": "Object",
        "set": "bound value()",
        "get": "bound value()",
        "fetchMissingUsers": "bound value()",
        "fetchBasicUsers": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      },
      "roomStore": {
        "instance": "Object",
        "userStore": "Object",
        "isSubscribedTo": "isSubscribedTo()",
        "logger": "Object",
        "rooms": "Object",
        "setSync": "bound value()",
        "set": "bound value()",
        "get": "bound value()",
        "popSync": "bound value()",
        "pop": "bound value()",
        "addUserToRoom": "bound value()",
        "removeUserFromRoom": "bound value()",
        "updateSync": "bound value()",
        "update": "bound value()",
        "fetchBasicRoom": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      }
    },
    "100344055": {
      "id": 100344055,
      "senderId": "1",
      "roomId": "b303155f-7baf-4fc0-92bc-c90caa223be0",
      "createdAt": "2019-09-09T13:35:17Z",
      "updatedAt": "2019-09-09T13:35:17Z",
      "text": "dsad",
      "userStore": {
        "instance": "Object",
        "presenceStore": "Object",
        "logger": "Object",
        "reqs": "Object",
        "onSetHooks": "Array[1]",
        "users": "Object",
        "set": "bound value()",
        "get": "bound value()",
        "fetchMissingUsers": "bound value()",
        "fetchBasicUsers": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      },
      "roomStore": {
        "instance": "Object",
        "userStore": "Object",
        "isSubscribedTo": "isSubscribedTo()",
        "logger": "Object",
        "rooms": "Object",
        "setSync": "bound value()",
        "set": "bound value()",
        "get": "bound value()",
        "popSync": "bound value()",
        "pop": "bound value()",
        "addUserToRoom": "bound value()",
        "removeUserFromRoom": "bound value()",
        "updateSync": "bound value()",
        "update": "bound value()",
        "fetchBasicRoom": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      }
    },
    "100344056": {
      "id": 100344056,
      "senderId": "1",
      "roomId": "b303155f-7baf-4fc0-92bc-c90caa223be0",
      "createdAt": "2019-09-09T13:36:52Z",
      "updatedAt": "2019-09-09T13:36:52Z",
      "text": "sfsd",
      "userStore": {
        "instance": "Object",
        "presenceStore": "Object",
        "logger": "Object",
        "reqs": "Object",
        "onSetHooks": "Array[1]",
        "users": "Object",
        "set": "bound value()",
        "get": "bound value()",
        "fetchMissingUsers": "bound value()",
        "fetchBasicUsers": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      },
      "roomStore": {
        "instance": "Object",
        "userStore": "Object",
        "isSubscribedTo": "isSubscribedTo()",
        "logger": "Object",
        "rooms": "Object",
        "setSync": "bound value()",
        "set": "bound value()",
        "get": "bound value()",
        "popSync": "bound value()",
        "pop": "bound value()",
        "addUserToRoom": "bound value()",
        "removeUserFromRoom": "bound value()",
        "updateSync": "bound value()",
        "update": "bound value()",
        "fetchBasicRoom": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      }
    },
    "100344057": {
      "id": 100344057,
      "senderId": "1",
      "roomId": "b303155f-7baf-4fc0-92bc-c90caa223be0",
      "createdAt": "2019-09-09T13:37:43Z",
      "updatedAt": "2019-09-09T13:37:43Z",
      "text": "dsadas",
      "userStore": {
        "instance": "Object",
        "presenceStore": "Object",
        "logger": "Object",
        "reqs": "Object",
        "onSetHooks": "Array[1]",
        "users": "Object",
        "set": "bound value()",
        "get": "bound value()",
        "fetchMissingUsers": "bound value()",
        "fetchBasicUsers": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      },
      "roomStore": {
        "instance": "Object",
        "userStore": "Object",
        "isSubscribedTo": "isSubscribedTo()",
        "logger": "Object",
        "rooms": "Object",
        "setSync": "bound value()",
        "set": "bound value()",
        "get": "bound value()",
        "popSync": "bound value()",
        "pop": "bound value()",
        "addUserToRoom": "bound value()",
        "removeUserFromRoom": "bound value()",
        "updateSync": "bound value()",
        "update": "bound value()",
        "fetchBasicRoom": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      }
    },
    "100344058": {
      "id": 100344058,
      "senderId": "1",
      "roomId": "b303155f-7baf-4fc0-92bc-c90caa223be0",
      "createdAt": "2019-09-09T13:37:43Z",
      "updatedAt": "2019-09-09T13:37:43Z",
      "text": "dsa",
      "userStore": {
        "instance": "Object",
        "presenceStore": "Object",
        "logger": "Object",
        "reqs": "Object",
        "onSetHooks": "Array[1]",
        "users": "Object",
        "set": "bound value()",
        "get": "bound value()",
        "fetchMissingUsers": "bound value()",
        "fetchBasicUsers": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      },
      "roomStore": {
        "instance": "Object",
        "userStore": "Object",
        "isSubscribedTo": "isSubscribedTo()",
        "logger": "Object",
        "rooms": "Object",
        "setSync": "bound value()",
        "set": "bound value()",
        "get": "bound value()",
        "popSync": "bound value()",
        "pop": "bound value()",
        "addUserToRoom": "bound value()",
        "removeUserFromRoom": "bound value()",
        "updateSync": "bound value()",
        "update": "bound value()",
        "fetchBasicRoom": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      }
    },
    "100344059": {
      "id": 100344059,
      "senderId": "1",
      "roomId": "b303155f-7baf-4fc0-92bc-c90caa223be0",
      "createdAt": "2019-09-09T13:37:44Z",
      "updatedAt": "2019-09-09T13:37:44Z",
      "text": "wqe",
      "userStore": {
        "instance": "Object",
        "presenceStore": "Object",
        "logger": "Object",
        "reqs": "Object",
        "onSetHooks": "Array[1]",
        "users": "Object",
        "set": "bound value()",
        "get": "bound value()",
        "fetchMissingUsers": "bound value()",
        "fetchBasicUsers": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      },
      "roomStore": {
        "instance": "Object",
        "userStore": "Object",
        "isSubscribedTo": "isSubscribedTo()",
        "logger": "Object",
        "rooms": "Object",
        "setSync": "bound value()",
        "set": "bound value()",
        "get": "bound value()",
        "popSync": "bound value()",
        "pop": "bound value()",
        "addUserToRoom": "bound value()",
        "removeUserFromRoom": "bound value()",
        "updateSync": "bound value()",
        "update": "bound value()",
        "fetchBasicRoom": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      }
    },
    "100344060": {
      "id": 100344060,
      "senderId": "1",
      "roomId": "b303155f-7baf-4fc0-92bc-c90caa223be0",
      "createdAt": "2019-09-09T13:37:45Z",
      "updatedAt": "2019-09-09T13:37:45Z",
      "text": "ewqe",
      "userStore": {
        "instance": "Object",
        "presenceStore": "Object",
        "logger": "Object",
        "reqs": "Object",
        "onSetHooks": "Array[1]",
        "users": "Object",
        "set": "bound value()",
        "get": "bound value()",
        "fetchMissingUsers": "bound value()",
        "fetchBasicUsers": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      },
      "roomStore": {
        "instance": "Object",
        "userStore": "Object",
        "isSubscribedTo": "isSubscribedTo()",
        "logger": "Object",
        "rooms": "Object",
        "setSync": "bound value()",
        "set": "bound value()",
        "get": "bound value()",
        "popSync": "bound value()",
        "pop": "bound value()",
        "addUserToRoom": "bound value()",
        "removeUserFromRoom": "bound value()",
        "updateSync": "bound value()",
        "update": "bound value()",
        "fetchBasicRoom": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      }
    },
    "100344061": {
      "id": 100344061,
      "senderId": "1",
      "roomId": "b303155f-7baf-4fc0-92bc-c90caa223be0",
      "createdAt": "2019-09-09T13:37:47Z",
      "updatedAt": "2019-09-09T13:37:47Z",
      "text": "dsa",
      "userStore": {
        "instance": "Object",
        "presenceStore": "Object",
        "logger": "Object",
        "reqs": "Object",
        "onSetHooks": "Array[1]",
        "users": "Object",
        "set": "bound value()",
        "get": "bound value()",
        "fetchMissingUsers": "bound value()",
        "fetchBasicUsers": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      },
      "roomStore": {
        "instance": "Object",
        "userStore": "Object",
        "isSubscribedTo": "isSubscribedTo()",
        "logger": "Object",
        "rooms": "Object",
        "setSync": "bound value()",
        "set": "bound value()",
        "get": "bound value()",
        "popSync": "bound value()",
        "pop": "bound value()",
        "addUserToRoom": "bound value()",
        "removeUserFromRoom": "bound value()",
        "updateSync": "bound value()",
        "update": "bound value()",
        "fetchBasicRoom": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      }
    },
    "100346696": {
      "id": 100346696,
      "senderId": "1",
      "roomId": "b303155f-7baf-4fc0-92bc-c90caa223be0",
      "createdAt": "2019-09-10T08:07:33Z",
      "updatedAt": "2019-09-10T08:07:33Z",
      "text": "dsadas das",
      "userStore": {
        "instance": "Object",
        "presenceStore": "Object",
        "logger": "Object",
        "reqs": "Object",
        "onSetHooks": "Array[1]",
        "users": "Object",
        "set": "bound value()",
        "get": "bound value()",
        "fetchMissingUsers": "bound value()",
        "fetchBasicUsers": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      },
      "roomStore": {
        "instance": "Object",
        "userStore": "Object",
        "isSubscribedTo": "isSubscribedTo()",
        "logger": "Object",
        "rooms": "Object",
        "setSync": "bound value()",
        "set": "bound value()",
        "get": "bound value()",
        "popSync": "bound value()",
        "pop": "bound value()",
        "addUserToRoom": "bound value()",
        "removeUserFromRoom": "bound value()",
        "updateSync": "bound value()",
        "update": "bound value()",
        "fetchBasicRoom": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      }
    },
    "100346697": {
      "id": 100346697,
      "senderId": "1",
      "roomId": "b303155f-7baf-4fc0-92bc-c90caa223be0",
      "createdAt": "2019-09-10T08:07:36Z",
      "updatedAt": "2019-09-10T08:07:36Z",
      "text": "asdsa",
      "userStore": {
        "instance": "Object",
        "presenceStore": "Object",
        "logger": "Object",
        "reqs": "Object",
        "onSetHooks": "Array[1]",
        "users": "Object",
        "set": "bound value()",
        "get": "bound value()",
        "fetchMissingUsers": "bound value()",
        "fetchBasicUsers": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      },
      "roomStore": {
        "instance": "Object",
        "userStore": "Object",
        "isSubscribedTo": "isSubscribedTo()",
        "logger": "Object",
        "rooms": "Object",
        "setSync": "bound value()",
        "set": "bound value()",
        "get": "bound value()",
        "popSync": "bound value()",
        "pop": "bound value()",
        "addUserToRoom": "bound value()",
        "removeUserFromRoom": "bound value()",
        "updateSync": "bound value()",
        "update": "bound value()",
        "fetchBasicRoom": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      }
    },
    "100346698": {
      "id": 100346698,
      "senderId": "1",
      "roomId": "b303155f-7baf-4fc0-92bc-c90caa223be0",
      "createdAt": "2019-09-10T08:07:37Z",
      "updatedAt": "2019-09-10T08:07:37Z",
      "text": "dsa",
      "userStore": {
        "instance": "Object",
        "presenceStore": "Object",
        "logger": "Object",
        "reqs": "Object",
        "onSetHooks": "Array[1]",
        "users": "Object",
        "set": "bound value()",
        "get": "bound value()",
        "fetchMissingUsers": "bound value()",
        "fetchBasicUsers": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      },
      "roomStore": {
        "instance": "Object",
        "userStore": "Object",
        "isSubscribedTo": "isSubscribedTo()",
        "logger": "Object",
        "rooms": "Object",
        "setSync": "bound value()",
        "set": "bound value()",
        "get": "bound value()",
        "popSync": "bound value()",
        "pop": "bound value()",
        "addUserToRoom": "bound value()",
        "removeUserFromRoom": "bound value()",
        "updateSync": "bound value()",
        "update": "bound value()",
        "fetchBasicRoom": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      }
    },
    "100391955": {
      "id": 100391955,
      "senderId": "37162",
      "roomId": "b303155f-7baf-4fc0-92bc-c90caa223be0",
      "createdAt": "2019-09-25T14:11:45Z",
      "updatedAt": "2019-09-25T14:11:45Z",
      "text": "пваыпы",
      "userStore": {
        "instance": "Object",
        "presenceStore": "Object",
        "logger": "Object",
        "reqs": "Object",
        "onSetHooks": "Array[1]",
        "users": "Object",
        "set": "bound value()",
        "get": "bound value()",
        "fetchMissingUsers": "bound value()",
        "fetchBasicUsers": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      },
      "roomStore": {
        "instance": "Object",
        "userStore": "Object",
        "isSubscribedTo": "isSubscribedTo()",
        "logger": "Object",
        "rooms": "Object",
        "setSync": "bound value()",
        "set": "bound value()",
        "get": "bound value()",
        "popSync": "bound value()",
        "pop": "bound value()",
        "addUserToRoom": "bound value()",
        "removeUserFromRoom": "bound value()",
        "updateSync": "bound value()",
        "update": "bound value()",
        "fetchBasicRoom": "bound value()",
        "snapshot": "bound value()",
        "getSync": "bound value()",
        "decorate": "bound value()"
      }
    }
  },
  "createConvo": "createConvo()"
}


export default App;